# Generated by Django 5.0.6 on 2024-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
