# Generated by Django 5.0.6 on 2024-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_livros_editora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
    ]
