# Generated by Django 5.0.6 on 2024-05-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_categoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
