# Generated by Django 5.0.6 on 2024-05-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_livros_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
