# Generated by Django 5.0.6 on 2024-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_livros_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro/'),
        ),
    ]
