# Generated by Django 5.0.6 on 2024-05-20 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_livros_imagem'),
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='nome_emprestado_anonimo',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_usuario', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
