# Generated by Django 5.0.6 on 2024-05-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_remove_emprestimos_avaliacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='nome_emprestado',
            new_name='usuario_emprestado',
        ),
    ]
