# Generated by Django 5.0.6 on 2024-05-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_rename_nome_emprestado_emprestimos_usuario_emprestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='usuario_emprestado',
            new_name='nome_emprestado',
        ),
    ]
