# Generated by Django 5.0.6 on 2024-05-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_rename_usuario_emprestado_emprestimos_nome_emprestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.emprestimos')),
            ],
            options={
                'verbose_name': 'Devolução',
            },
        ),
    ]
