# Generated by Django 5.0.6 on 2024-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='status',
            field=models.CharField(choices=[('E', 'Emprestado'), ('D', 'Devolvido')], default='E', max_length=1),
        ),
    ]
